openapi: 3.0.0
info:
  version: 0.0.0
  title: Events (WIP)
paths:
  /:
    get:
      summary: Swims API Events
      responses:
        '201':
          description: Webhook created
      callbacks: # Callback definition
        memberRegistered: # Event name
          'Member Registration Complete': # The callback URL,
            # Refers to the passed URL
            post:
              requestBody: # Contents of the callback message
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        eventType:
                          type: string
                          example: Member Registration Complete
                        oid:
                          type: string
                          example: EFD6F74613444017B0DB1884AADBC117
                        eventSequence:
                          type: number
                          example: 1234
                        eventDate:
                          type: object
                          properties:
                            vendorRecordId:
                              type: string
                              example: DB1884AADBC117
                            memberIds:
                              type: array
                              items:
                                type: string
                                example: 720B84E9E96FAC

                      required:
                        - message
              responses: # Expected responses to the callback message
                '200':
                  description: Your server returns this code if it accepts the callback
